---
title: "Documentation"
author: "Xiufu Yao & Sven Herbold"
date: "5 August 2019"
output: html_document
---


## Komponenten tidyen

Sven und Xiufu basieren die R Projekte auf die Arbeit bisher von Marcel (2 August 2019)

Nach dem rebase auf Marcels Script haben wir die gleiche tidy_data.R Datei für die Änderung und Imports Der Komponenten angepasst -> umbenannt in tidy_data_Komponente.R

Wir nehmen an, das Datum wurde als 5 Stellige Zahl an das Origin 1970-1-1 addiert. Ist das eine Norm?

### Probleme

1. Dateien beinhalten " ", lassen sich nicht mit read_csv2 einlesen (read_csv sollte extra für den Euro Raum verwendet werden, Marcel hatte es für seine Parts import Commands verwendet)
   * Da die vorhandenen CSV und TXT Dateien unterschiedlich "" haben oder nicht, muss Der R Code auf diesen Punkt beim Import jedes Mal prüfen
   * ist "" überhaupt ein Problem? alle haben "" und SEP = ; oder SEP = , sollte in einfachen Fällen der Einzige Unterschied sein
2. Es sind verschiedene Patterns für die Dateien vorhanden. Die schwierigsten haben Kopftzeilen .x .y und die Werte rutschen zwischen den Kopfzeilen. Diese Patterns müssen alle einzeln hergeleitet werden, um die richtige Einlesefunktion und Säuberung im Code zu ermöglichen, alle müssen quasi individuell bearbeitet werden
   * Gerade hier, wo man nicht weiß, in welcher Zeile die Werte weiterrutschen, muss vielleicht eine query im R Code eingesetzt werden, um den Code für die Säuberung zu rechtfertigen
   * auch wird ein query wichtig, da meine Anzeige in Excel vielleicht nicht die gesamte Datei offen hat? Allerdings entnahm ich meine Werte dem x1 col, diese sollte eindeutig sein
3. Dateien sind in unterschiedlichem Format vorhanden (.txt und .csv). Diese zu öffnen erfordert unterschiedliche Funktionen: read.csv oder read.delim oder die readr Version read_csv bzw. read_delim. Allerdings ist keine offensichtliche Reihenfolge für die unterschiedlichen Dateiendungen zu erkennen, wenn nicht automatisiert werden kann, muss jede Datei manuell mit einer Funktion eingelesen werden
   * Gut formatierte .txt Dateien über read.table() einlesbar, aber nicht formatierte .txt Dateien ohne Zeilenenden nicht, wie kann das Zeilenende vermittelt werden?
4. Es kann sein, dass die Aufgabenstellung erfordert, dass für die endgültige Shiny App ein Filter für die OEM Werke benötigt wird. Die Werke sind vielleicht im Ordner Geodaten zu finden. Eventuell müssen hier später Werknamen (Locations) die 3-stelligen Werksnummern ersetzen.

### Lösung?

* Eine Funktion, die alle Dokumente in einem Ordner durchzählt (while Schleife?)
* Eine Funktion, die prüft, ob "" in Der jetzt bevorstehend zu importierenden Datei vorkommt
* Eine Funktion, die entscheidet, ob read_csv oder csv2 je nach "" Existenz für die anstehende Datei benutzt wird
* Eine Funktion, die prüft, ob Eine CSV oder Eine TXT Datei ansteht und welche Formel (read_csv, read_delim) dafür genutzt wird







## Generelle Überlegungen

Wenn nur die Produktionsdauer eines Wagentyps wichtig ist, zählt nur das frühste Produktionsdatum eines der 4 Teile, Komponente sind somit völlig unwichtig, da nur das Produktionsdatum des fertigen Wagentyps wieder relevant wird

* Ist zumindest das Datum der Komponenten irrelevant? Komponenten werden nur benötigt, um die Teile zu den Wagentypen zuzuordnen?

